name: /mixfound
channels:
  - https://mirrors.sustech.edu.cn/anaconda/cloud/conda-forge
  - anaconda
  - https://mirrors.sustech.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.sustech.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py39h06a4308_0
  - cffi=1.15.0=py39hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=3.9.0=py39he06866b_0
  - hdf5=1.12.1=h70be1eb_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.2.0=py39h06a4308_0
  - jpeg=9e=h7f8727e_0
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.20.1=h568e23c_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libcurl=8.2.1=h91b91d3_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.15.8=h780b84a_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.1=py39h06a4308_1
  - matplotlib-base=3.5.1=py39ha18d171_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - pcre=8.45=h295c915_0
  - pip=21.2.4=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch-mutex=1.0=cuda
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - tensorboardx=2.5.1=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h1ccaba5_1
  - tornado=6.1=py39h27cfd23_0
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.4.9=haebb681_0
  - pip:
      - absl-py==1.0.0
      - accelerate==1.6.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiohttp-cors==0.8.1
      - aiosignal==1.3.2
      - airportsdata==20250224
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.3.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - apex==0.1
      - astor==0.8.1
      - asttokens==2.4.1
      - async-timeout==5.0.1
      - attrs==23.2.0
      - av==14.3.0
      - blake3==1.0.4
      - cachetools==5.0.0
      - click==8.1.7
      - clip==1.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - colorful==0.5.6
      - compressed-tensors==0.9.1
      - crcmod==1.7
      - datasets==3.5.0
      - decorator==5.1.1
      - depyf==0.18.0
      - dictances==1.5.3
      - diffusers==0.29.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - dnspython==2.6.1
      - easydict==1.9
      - easydl==2.2.0
      - einops==0.4.1
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - faiss-gpu==1.7.2
      - fastapi==0.111.1
      - fastapi-cli==0.0.4
      - ffmpy==0.4.0
      - filelock==3.18.0
      - frozenlist==1.6.0
      - fsspec==2024.6.0
      - ftfy==6.1.1
      - gguf==0.10.0
      - google-api-core==2.24.2
      - google-auth==2.39.0
      - google-auth-oauthlib==0.4.6
      - googleapis-common-protos==1.70.0
      - gradio==4.29.0
      - gradio-client==0.16.1
      - gradio-imageslider==0.0.20
      - grpcio==1.44.0
      - h11==0.14.0
      - hausdorff==0.2.6
      - hdf5plugin==5.1.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.29.1
      - imageio==2.35.1
      - imbalanced-learn==0.12.2
      - imblearn==0.0
      - importlib-metadata==4.11.3
      - importlib-resources==6.4.0
      - interegular==0.3.3
      - ipdb==0.13.13
      - ipython==8.18.1
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.9.0
      - jmespath==0.10.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - lark==1.2.2
      - lazy-loader==0.4
      - llvmlite==0.38.1
      - lm-format-enforcer==0.10.11
      - markdown==3.3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - miseval==1.2.2
      - mistral-common==1.5.4
      - model-index==0.1.11
      - monai==1.4.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - numba==0.55.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.0
      - openai==1.75.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python==4.5.5.64
      - opencv-python-headless==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.5
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - orjson==3.10.6
      - oss2==2.17.0
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==24.2
      - pandas==1.4.2
      - parso==0.8.3
      - partial-json-parser==0.2.1.1.post5
      - pathlib2==2.3.7.post1
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.7
      - pot==0.8.1.0
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.43
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==6.30.2
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyarrow==19.0.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycountry==24.6.1
      - pycryptodome==3.21.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydub==0.25.1
      - pygments==2.17.2
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2023.4
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==26.4.0
      - qwen-vl-utils==0.0.10
      - ray==2.44.1
      - referencing==0.35.1
      - regex==2023.10.3
      - requests==2.32.3
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rpds-py==0.19.1
      - rsa==4.8
      - ruff==0.5.5
      - safetensors==0.4.3
      - scikit-image==0.21.0
      - scikit-learn==1.4.2
      - scipy==1.11.4
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - setuptools==60.2.0
      - shellingham==1.5.4
      - smart-open==7.1.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.37.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.9.0
      - tensorboard-data-server==0.6.1
      - tensorboard-logger==0.1.0
      - tensorboard-plugin-wit==1.8.1
      - termcolor==1.1.0
      - thop==0.1.1-2209072238
      - tifffile==2024.8.30
      - tiktoken==0.9.0
      - timm==1.0.13
      - tokenizers==0.21.0
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.5.1
      - torch-tb-profiler==0.4.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - traitlets==5.14.2
      - triton==3.1.0
      - trl==0.14.0
      - tsne-torch==1.0.1
      - typer==0.12.3
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - urllib3==1.26.20
      - uvicorn==0.30.3
      - uvloop==0.19.0
      - virtualenv==20.30.0
      - vllm==0.7.2
      - watchfiles==0.22.0
      - wcwidth==0.2.8
      - websockets==11.0.3
      - werkzeug==2.1.2
      - wrapt==1.17.2
      - xformers==0.0.28.post3
      - xgrammar==0.1.18
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.20.0
      - zipp==3.8.0
